server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://alan-db.copptkzflkpr.ap-northeast-2.rds.amazonaws.com:5432/alan_db?currentSchema=bokduck
    username: alan
    password: CJpWV2FZaO
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
springdoc:
  packages-to-scan: com.bokduck

mybatis:
  mapper-locations: classpath:mybatis/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.bokduck.api.**.infra
